language: csharp
solution: SharpMap.sln
install:
  - nuget restore SharpMap.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild SharpMap.sln /p:Configuration=ReleaseLinux;UseTools35=false
